[tool.ruff]
# Проверка стиля и автофиксы
line-length = 88
lint.select = ["E", "W", "F", "C90", "I"]
# Автофикс там, где возможно (trailing spaces, пустые строки, отступы)
fix = true

# Конкретные ошибки для пробелов и пустых строк
lint.ignore = []
# W291 — trailing whitespace
# W293 — blank line contains whitespace
# E302 — две пустые строки перед top-level функцией или классом
# E305 — одна пустая строка внутри класса между методами

[tool.black]
line-length = 88
target-version = ["py310"]
# Black автоматически форматирует длинные аргументы функций и строки
